package br.com.delxmobile.qconsp.scripts;

import br.com.delxmobile.qconsp.database.RepositorioPalestrante;
import br.com.delxmobile.qconsp.util.SQLiteHelper;
import android.content.Context;

public class RepositorioPalestranteScript extends RepositorioPalestrante {

	// Script para fazer drop na tabela
	private static final String SCRIPT_DATABASE_DELETE = "DROP TABLE IF EXISTS palestra";

	// Cria a tabela com o "_id" sequencial
	private static final String[] SCRIPT_DATABASE_CREATE = new String[] {
	"create table palestrante ( _id integer primary key autoincrement, nome text not null, perfil text not null, palestra text not null, foto text not null);",
	"insert into palestrante (nome, perfil, palestra, foto) values('Adriano Almeida', 'Trabalha desde 2008 pela Caelum como consultor, desenvolvedor e instrutor. Já palestrou em eventos importantes no Brasil como o QCon e OxenteRails e também no exterior (Devoxx, na Bélgica) e participa de projetos opensource como o VRaptor. Também possui artigos publicados em revistas brasileiras sobre a plataforma Java em geral. Também desenvolve com Ruby e Rails e é um dos instrutores da formação Rails. Gosta de aprender novos paradigmas de programação e formas mais simples de resolver problemas.', 'Apresentação', '0');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Alberto Souza', 'Instrutor pela Caelum, Alberto criou junto com Anderson Leite o Agendatech e está envolvido com o andamento de Scala+Java no Brasil. ', 'Scala como alternativa para aplicações puramente Java', '1');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Alexandre Freire', 'Alexandre Freire é mestre em Ciência da Computação no IME/USP. Sua dissertação versa sobre o Ensino de Metodologias Ágeis na Academia, na Indústria e no Governo . Atuou como desenvolvedor e líder de equipes em empresas, ONGs e no governo. Lecionou nos Cursos de Verão e como assistente de ensino em turmas de pós-graduação no IME/USP. Hoje é gerente da equipe de SaaS na Locaweb. Está frustrado com a falta de qualidade que é norma na indústria. Tenta colocar a ciência de volta na computação, extrapolando os limites da agilidade sem xiitismos. Como artista desenvolve trabalhos que investigam as táticas criativas da convivência em ambientes que se integram à natureza de forma sustentável. ', 'Dívida técnica: precisando de crédito? Quão fundo entrar e como evitar que o cobrador bata na sua porta', '2');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Alex Tabor', 'Formado em Ciências da Computação pela University of Southern California, Alex Tabor é especialista em desenvolvimento de software e trabalhou como software architect da power.com, uma integradora de redes sociais, que em três anos atingiu a marca de 15 milhões de usuários. Sua identificação com a informática vem desde a infância, quando, aos 13 anos, lançou a primeira comunidade gráfica online da Índia, uma BBS (Bulletin Board System).', 'Peixe Urbano: Desafios e Soluções Tecnológicas para potencializar um crescimento acelerado', '3');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Anderson Leite', 'Instrutor, consultor e desenvolvedor pela Caelum, é formado em Engenharia de Computação pela Escola de Engenharia Mauá. Participa ativamente da comunidade Ruby tendo palestrado em eventos como RejectConf 07, RubyConf Brasil 2010, QCon 2010. É um dos organizadores do GURU-SP onde ajudou a criar projetos como Agendatech.com.br e Call4Paperz.com no Rails Rumble. É instrutor e um dos criadores da Formação Ruby on Rails da Caelum.', 'Apresentação', '4');",
	"insert into palestrante (nome, perfil, palestra, foto) values('André Faria Gomes', 'André Faria Gomes é arquiteto de software na Bluesoft Consultoria em São Paulo, bacharel em Sistemas de Informação pela FIAP. O foco principal de seu trabalho é na aplicação e coaching de métodos ágeis e no desenvolvimento de projetos de software em diversas linguagens e plataformas. Com mais de 9 anos de experiência trabalhou além de Java com tecnologias como Groovy, Ruby, C++, Php, Asp e Delphi. Faz parte do time do Agile Podcast, um podcast em inglês sobre métodos ágeis e do Bluesoft Podcast, um podcast em português sobre métodos ágeis. Mantém seu blog em andrefaria.com ', 'Lições aprendidas em 4 anos de agilidade', '5');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Andrews Medina', 'Apenas um rapaz latino americano, entusiasta de Python, Django e TDD, Andrews atua como desenvolvedor web na globo.com. Nos momentos livres dedica-se ao rock, surf, skate e no desenvolvimento de projetos open source. Participa da liderança da comunidade Django Brasil, é moderador da lista Python Brasil e co-fundador do #cobrateam.', 'Os complicados testes de interfaces e componentes web', '6');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Bruno Andrade Alves', 'Bruno Andrade Alves é graduado em Ciência da Computação e possui experiência no mercado nacional e internacional, tanto na área de infra-estrutura como na área de desenvolvimento, tendo atuado na infra de grandes projetos do governo e da iniciativa privada incluindo instituição financeira em Londres. Possui vasta experiência em sistemas web, sendo hoje professor do curso de pós-graduação de desenvolvimento de sistemas web da Pucminas. Sócio-fundador da Dito Internet atualmente é o responsável pela área de tecnologia da empresa, tendo atuado em vários projetos de sucesso que atendem milhões de usuários como odrible.com, DengueVille, Seu Ouvido vale um chip, além de ser co-idealizador do Organizaí, o primeiro serviço para organizar seus cupons de compra coletiva no Brasil.', 'Arquitetura escalável com Ruby On Rails, Node.js e Redis', '7');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Bruno Borges', 'Profissional da área há 10 anos com atuação em empresas como EDS/HP, CETIP, Summa Technologies, CETIP, Neociclo e agora arquiteto de sistemas na wdev; Especialista em softwares e padrões de integração (EIPs), soluções web, soluções orientadas a serviços e componentização de aplicativos. Membro de comunidades de software livre (RioJUG, SouJava, Apache Software Foundation). Fundador do grupo Wicket em Português, contribuidor para projetos Open Source da ASF, criador do projeto Apache Camel Social e presente nos principais eventos da comunidade Java no Brasil e no exterior. ', 'Java mais ágil que nunca no desenvolvimento Web', '8');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Bruno Pereira', 'Gerente de operações e pré-venda na Concrete Solutions, atualmente responsável pelo escritório de SP. Trabalhou em grandes projetos na Globo.com, Globosat, Alcoa, White Martins e outros clientes. Cursou engenharia eletrônica e de computação na UFRJ. Trabalhou em muitos projetos web, com expertise no server-side e client-side. Foi também um dos pioneiros na adoção de REST no Brasil. ', 'Transações compensatórias usando REST', '9');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Cecilia Fernandes', 'Cecilia Fernandes é desenvolvedora, consultora e instrutora entusiasta da agilidade pragmática. Hoje, ela foca seus estudos na evolução da agilidade e palestrou sobre o assunto em conferências brasileiras como Agile Brazil, Agile Vale e Oxente Rails. Em 2009, Cecilia desenvolveu o curso PM-83, introdutório em Scrum. Ela, contudo, crê que ninguém pode entender Scrum a contento sem uma base sólida em Agile, nem fazer bom uso dele sem boas práticas de desenvolvimento - e se empenha em difundir essa mensagem em suas aulas e na comunidade ágil. ', 'Melhorando um ambiente ágil', '10');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Christiano Milfont', 'Christiano Milfont é coordenador dos grupos XPCE, GURUCE, CEARAJS e JAVACE, programador, palestrante, “evangilista” (evangelista ágil), blogger, ex-colunista da revista Java Magazine, líder da Milfont Consulting, tem mais de 10 anos de experiência em desenvolvimento de software, uma década com Java, alguns pouco anos com Ruby/Rails, maluco por Javascript, organizou os eventos Maré de Agilidade Fortaleza 2009/2010 e BrazilJS, é atleta e headbanger. ', 'Combinando Programação funcional e O.O. em javascript de forma prática', '11');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Cristiano Sanchez', 'Graduado em matemática, programador veterano, trabalhou com LISP, C++ e principalmente Java. Instrutor na Sun Microsystems por mais de 8 anos. Atualmente está à frente da equipe de desenvolvimento do Lab360 gerenciando e programando projetos em RoR e Objective-C.', 'Aplicações Móveis Híbridas: usando Web e Nativo juntos', '12');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Daniel Destro', 'Daniel Destro é formado em Ciências da Computação pela PUC-SP (2000) e pós-graduado em MBA pelo IPT/USP. Trabalha com desenvolvimento de software há 12 anos, passando pela consultoria Discover Technology como desenvolvedor e arquiteto de software e está no SPC Brasil desde 2010. Tem dezenas de artigos publicados no GUJ e Java Magazine. Tem experiência em desenvolvimento de software voltado ao ambiente internet com a plataforma Java, incluindo sistemas críticos e de alta disponibilidade', 'Arquitetura de um sistema crítico de alta disponibilidade com soluções open source', '13');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Daniel Sobral', 'Consultor em TI especialista em sistemas *NIX pela Tecnisys, foi desenvolvedor do FreeBSD (committer), e conta com 15 anos de experiência nas áreas de segurança, gerência de projeto, desenvolvimento de software, administração de servidores e redes de comunicação. Frequente participante da lista Scala Brasil. ', 'Uma plataforma para o desenvolvimento de sistemas concorrentes e distribuídos para a JVM', '14');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Danilo Sato', 'Danilo Sato é desenvolvedor de software há 10 anos, trabalhando com Métodos Ágeis há 7 anos e consultor da ThoughtWorks há 3 anos, atuando nos mais diversos papéis: desenvolvedor, agile coach, arquiteto, treinador e líder técnico em projetos Ruby e Java no Brasil, EUA e em UK. Com experiência como palestrante em conferências nacionais e internacionais, Danilo já apresentou na XP 2007, XP 2009, XP 2010, Agile 2008, Agile 2009, Ágiles 2008, Falando em Agile 2008, Rails Summit Latin America 2008, Agile Brazil 2011, além de ser o fundador do Coding Dojo @ São Paulo e organizador da Agile Brazil 2010 e 2011. ', 'Refatoração em larga escala', '15');",
	"insert into palestrante (nome, perfil, palestra, foto) values('David Paniz', 'É graduado e pós-graduado pela Faculdade de Informática e Administração Paulista e possui aproximadamente 5 anos de experiência com desenvolvimento de software, sendo 3 na Caelum. Adora aprender novas tecnologias e desenvolver para a Web. É consultor e instrutor da Caelum.', '', '16');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Edward Ribeiro', 'Edward Ribeiro é mestre em Informática pela Universidade de Brasília (2006). Atualmente ocupa o cargo de analista de sistema do Prodasen (Senado Federal), tendo trabalhado anteriormente em vários órgãos do legislativo e judiciário federal, além de ministrar aulas em faculdades e universidade privadas do Distrito Federal nas áreas de Sistemas Distribuídos, Sistemas Operacionais, Bancos de Dados e Linguagens de Programação. Além disso, desde 2008, desenvolve trabalhos de pesquisa em conjunto com professores da Universidade de Brasília na área de sistemas distribuídos e bioinformática com publicações nacionais e internacionais. Colaborou recentemente com softwares livres como Cassandra e VoltDB, submetendo patches, e participando de discussões e palestras sobre essas novas tecnologias. ', 'VoltDB - OLTP de alta performance', '17');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Emerson Macedo', 'Arquiteto/Desenvolvedor de Software com mais de 12 anos de experiência. Atualmente trabalha na Globo.com, sediado no Rio de Janeiro. Possui extensa experiência nos ramos de telecomunicações, bancos, seguradoras, portais de internet, entre outros. Entusiasta ágil há alguns anos, também é professor. Escreve regularmente em seu blog pessoal (http://codificando.com) e no blog visão ágil (http://visaoagil.wordpress.com/author/emerleite/). Atualmente, é precursor de Node.JS no Brasil, tendo escrito algumas bibliotecas e o site de screencasts NodeCasts.org. Também é professor online desta nova tecnologia nos cursos da e-Genial. ', 'Desenvolvimento de Jogos: A vez do Browser e do Node.JS', '18');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Evan Weaver', 'Evan Weaver is currently Twitter s architect. In his 3 years at Twitter, he has also been a performance engineer, technical lead, and engineering manager, at one point running the largest engineering team in the company. He specializes in scalability and distributed systems, and is a noted Ruby on Rails performance expert. Before Twitter, he worked at CNET Networks and SAP AG.', 'Engenharia de performance no Twitter', '19');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Fábio Akita', 'Fabio Akita é o criador do Rails Summit. Ele promove o uso do framework Rails desde 2006, mantém seu blog AkitaOnRails.com, e é proeminente evangelizador de novas ferramentas e metodologias ágeis. Atualmente trabalha na GoNow.', 'A Semente Não Entendida de Todas Metodologias Ágeis', '20');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Fernando de la Riva', 'Engenheiro de computação pela PUC-RJ, com MBA em Columbia GSB e na London Business School, pós-graduado em Gestão Empresarial pela COPPEAD. Empreendedor serial fundou cinco empresas de tecnologia nos últimos 13 anos. É Sócio-fundador da Concrete Solutions, onde ocupa o cargo de diretor executivo. Foi sócio-fundador da Atness Computing Services, consultor, gerente de projetos e COO da Teknoland do Brasil (empresa do Grupo GE & Telefônica). Como consultor de processos da K2 Achievements com foco em centrais de atendimento e serviços na área de Telecom, participou em projetos de reestruturação, revisão e sistematização de processos. Começou a carreira como especialista de produto e gerente comercial da NCD e da IBM (Risc 6000), através da Solvo.', 'Lean Startups', '21');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Flavio Torres', 'Administrador de sistemas e aplicações no iG. Possui sólidos conhecimentos no sistema operacional GNU/Linux para ambiente de missão crítica. Seu campo de atuação é com projetos que demandam alta disponibilidade e performance. É graduado em Redes e pós-graduado em Gestão de Redes e Segurança de Sistemas de Informação e Comunicação. ', 'Aceleração http com Varnish', '22');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Francisco Souza', 'Mundialmente conhecido no interior de Cachoeiro de Itapemirim, Francisco é membro do time de desenvolvimento do G1, portal de notícias da Globo.com, onde trabalha principalmente com Python e Django. É apaixonado por desenvolvimento de softwares, viciado em open source, associado à Associação Python Brasil e membro do #cobrateam. ', 'Os complicados testes de interfaces e componentes web', '23');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Guilherme Silveira', 'Líder técnico da Caelum, graduando em matemática aplicada na USP, ministrou diversas palestras relacionadas ao desenvolvimento na web. Junto com Paulo Silveira, criou o VRaptor em 2003. Atualmente tem o foco na implementação de integração de sistemas através de api s rest e seu impacto positivo no plano de negócios dos clientes da Caelum e é commiter de projetos como restfulie, xstream, paranamer e waffle com ênfase em Java e Ruby. É também responsável pelo conteúdo técnico dos cursos. ', 'Design de código: a qualidade que faz a diferença', '24');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Hanneli Tavante', 'Hanneli (a.k.a @hannelita) é uma desenvolvedora fissurada por programar, aprender novas linguagens, frameworks, explidor capacitores, programar em C pra relaxar e comittar código útil (ou não) em projetos Open Source aletórios que encontra vasculhando Githubs alheios. Ela também gosta de café, especialmente os do Starbucks ', '', '25');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Hiro Asari', 'Hiro Asari is a JRuby Support Engineer at Engine Yard, a PaaS company specializing in Ruby on Rails hosting. He has been involved with the JRuby project for more than 2 years, and has been a committer for over a year. ', 'Spring into Rails', '26');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Howard Dierking', 'Howard Dierking é gerente do time da WCF Web API, onde seu foco é em serviços HTTP e no AppFabric. Antes do WCF, Howard trabalhou como editor na MSDN Magazine, e também cuidou do programa de ceritificação no Microsoft Learning. Antes da Microsoft, ele passou 10 anos como desenvolvedor e arquiteto com foco em sistemas distribuídos. Howard vive em Redmond com sua esposa e duas filhas. ', 'REST e o Cloud: feitos um para o outro?', '27');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Jim Webber', 'Dr. Jim Webber is Chief Scientist with Neo Technology the company behind the popular open source graph database Neo4j, where he works on graph database server technology and writes open source software. Jim is interested in using big graphs like the Web for building distributed systems, which led him to being a co-author on the book REST in Practice, having previously written Developing Enterprise Web Services - An Architect s Guide. Jim is an active speaker, presenting regularly around the world. His blog is located at http://jimwebber.org and he tweets often @jimwebber. ', 'Aprendizados de grandes sistemas HTTP-centric', '28');",
	"insert into palestrante (nome, perfil, palestra, foto) values('John Rowell', 'John D. Rowell é programador e consultor de TI com 25 anos de experiência profissional. Trabalha principalmente com startups (próprias e de clientes), buscando sempre utilizar tecnologia de ponta para gerar eficiências e viabilizar produtos. Hoje seus focos de pesquisa e desenvolvimento incluem Ruby, NoSQL, cloud e sistemas distribuídos. Tweeta como @jdrowell. ', 'Entendendo sistemas distribuídos - CAP é só o começo!', '29');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Jorge Walendowsky', 'Graduado pela UFCG em Ciência da Computação, exerce a função de arquiteto de soluções há mais de 10 anos, especializando-se em arquiteturas de larga escala para lidar principalmente com sistemas financeiros. Atualmente trabalha no iG como Especialista de Sistemas, onde alia o know-how adquirido ao longo dos anos com o dinamismo de uma empresa de internet para conceber soluções versáteis e inovadoras para lidar com os mais diversos problemas. ', 'Edição de conteúdo web usando Javascript de ponta a ponta', '30');",
	"insert into palestrante (nome, perfil, palestra, foto) values('José Donizetti', 'Instrutor da Caelum, ativo palestrante e participa do treinamento de novos instrutores no Rio. ', '', '31');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Khawaja Shams', 'Khawaja Shams é membro do laborátorio de software de planejamento de operações (OPS) no NASA Jet Propulsion Laboratory. Khawaja desenvolve software para as operações dos robôs, incluindo terra, ar e água, como também as rovers de Marte. Ele lidera diversos projetos e trabalha nos componentes server side em Activity Planning e Sequencing Subsystem (APSS) para o Mars Science Laboratory. Khawaja trabalha com o escitório do CIO no JPL para co-liderar os esforços de colocar com segurança os benefícios do cloud nas diversas missões da NASA. Khawaja é graduado em computação pela UC San Diego, e mestrado pela Cornell. Atualmente realiza seu PhD em robótica na USC.', 'MythBusters - Mission Cloud Computing @ NASA.', '32');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Kunal Bhasin', 'Kunal Bhasin é CTO da Terracotta, onde cuida da evolução da plataforma, mentora os arquitetos e ajuda em outras iniciativas. Por 5 anos na Terracotta, Bhasin exerce papel fundamental nos maiores projetos da empresa em relação a escalabilidade, performance e disponibilidade. Bhasin têm muitos anos de experiência em uma grande variedade de sistemas, indo de projetos de temo real na NASA-Ames a aplicações de ecommerce. Trabalhou criando um framework de testes para robótica na NASA e como pesquisador na Canergir Mellon University, onde fez seu mestrado. ', 'Caching e NoSQL?', '33');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Leandro Daniel', 'Atua há mais de 13 anos como consultor de tecnologia da informação desempenhando atividades relacionadas a desenvolvimento e liderança de equipes. No início de 2009 realizou uma vontade antiga e começou a escrever artigos para a revista .net Magazine, onde procura contribuir com experiências vividas em projetos e boas práticas de desenvolvimento de software. Em 2010 se tornou Editor Técnico da mesma revista e passou a escrever também para a Easy .net Magazine. É um dos criadores do Void Podcast, onde conversa sobre vários assuntos relacionados a área de TI com alguns amigos. Pode ser encontrado no Twitter em @leandronet.', 'Aplicando a Arquitetura Evolucionária', '34');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Luca Bastos', 'Desenvolvedor do tempo da Carochinha que se mantém na ativa por pura paixão. Ávido leitor sendo o hábito da leitura um dos seus três principais prazeres na vida. Considera a curiosidade como sua principal qualidade. Continua como esforçado aprendiz na árdua, porém gostosa tentativa de se manter atualizado. Meninos eu vi. E vivi. Hoje trabalho na Concrete Solutions e desenvolvo usando Ruby e Rails, outra coisa que tive que reaprender na raça.', 'Transações compensatórias usando REST', '35');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Lucas Cavalcanti', 'Formado em Bacharelado de Ciências da Computação na USP, é consultor, instrutor e desenvolvedor na Caelum, participando de vários projetos envolvendo Java para Web, Scala e Agile. É um dos principais desenvolvedores da versão 3 do VRaptor, e contribui para diversos outros projetos open-source.', 'Scala como alternativa para aplicações puramente Java', '36');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Luiz Faias Junior', 'Trabalha com Java na Bluesoft desde 2002 e recentemente tem se aventurado pelo mundo do Ruby on Rails. Participa da comunidade de métodos ágeis desde 2007, compartilhando experiências sobre Scrum e Kanban no blog e podcast da Bluesoft. É também um dos criadores e contribuidores do projeto open source para gestão de projetos ágeis Pronto.', 'Lições aprendidas em 4 anos de agilidade', '37');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Mauricio Leal', 'Mauricio Leal é Arquiteto de Sistemas da RBS Digital, responsáveis por diversos sites do Grupo RBS. Já foi Gerente de Programas para Desenvolvedores da Sun Microsystems (hoje adquirida pela Oracle) e possui diversos anos com desenvolvimento em tecnologias cliente (desktop e móvel). Possui experiência em desenvolvimento de Sistemas em Países como Alemanha, França e Irlanda. Membro de um dos maiores Grupos de Usuarios de Java, o SouJava, vem trabalhando para o crescimento da comunidade e colaborado em discussões no cenário de tecnologias móveis e embarcadas baseadas em Java. ', 'Plataforma Java EE 7: Desenvolvendo para o Cloud', '38');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Mauricio Linhares', 'Maurício Linhares é desenvolvedor Java, Ruby e Objective-C, autor de um dos primeiros materiais sobre Objective-C em português e especialista em análise de performance de front ends de aplicações web. Começou sua carreira trabalhando com Java, escrevendo servidores para billing de aparelhos celulares. Foi evangelista da tecnologia, liderando o PBJUG, Grupo de Usuários Java da Paraíba e moderador do GUJ, blogando e fazendo palestras sobre tecnologias relacionadas, tendo publicado o primeiro artigo sobre o Spring Framework em português na revista Mundo Java. Mais tarde se envolveu com Ruby e Ruby on Rails, onde escreveu redes sociais, ferramentas de comércio eletrônico, gestão digital de documentos e plataformas SaaS para o mercado de imóveis, além de também blogar, principalmente sobre a tecnologia e manter alguns projetos open source, como o adaptador para se trabalhar com bancos de dados em modo mestre-escravo com ActiveRecord, o plugin master_slave_adapter. Atualmente tem se focado no desenvolvimento para as plataformas da Apple, com trabalhos em iOS e aplicações pra Mac, como o ScanDrop ( http://itunes.apple.com/br/app/scandrop/id412518240?mt=12 ), além de estar publicando material de introdução ao desenvolvimento de aplicações para iOS. ', 'iOS e sincronização de dados', '39');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Nelson Haraguchi', 'Desenvolvedor Ruby desde 2008, membro do GURU-SP, Fatecano e entusiasta do open-source. Sempre buscou o conhecimento sobre escalabilidade e otimização de sistemas em sua carreira. Especializado em otimização de sistemas Web, trabalha como líder técnico responsável pelo desenvolvimento e integração do sistema boo-box de advertising.', 'Escalando e Otimizando Projetos Legados', '40');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Paulo Silveira', 'Bacharel e mestre em Ciência da Computação pela USP, possui mais de 10 anos de experiência com desenvolvimento, passando pela Alemanha, pelo IBOPE e por dois anos como instrutor da Sun Microsystems. Coordena os cursos da Caelum nos cursos de verão da USP. Um dos fundadores do GUJ.com.br e é editor técnico da revista Mundo Java.', 'Apresentação', '41');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Pedro Brasileiro', 'Desenvolvedor do DETRAN-Ce, compondo atualmente na equipe de Arquitetura e Otimização. Já trabalhou com Java, SuperWaba, PHP, Asp.NET, Titanium e atualmente com alguns projetos Ruby on Rails (No qual se identifica mais). Trabalha criando soluções em Servidores Apache e Tomcat, como a OpenReport, que é usada atualmente para impressão de relatórios em Rails para arquivos gerados pelo iReport. ', '', '42');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Rafael Rosa', 'Rafael Rosa trabalha com desenvolvimento de software desde 95 e nos últimos anos tem focado em Ruby, metodos de desenvolvimento ágil e gestão de produtos. É formado em administração de empresas pela FEA/USP e atualmente é coordenador de produtos de infraestrutura na Locaweb, além de membro do Guru-SP, editor do Ruby Inside Brasil e um dos apresentadores do Grok Podcast.', 'Apresentação', '43');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Raphael Lacerda', 'Formado em Ciência da Computação pela Universidade Católica de Brasília e pós graduado em engenharia de sistemas, atua como desenvolvedor no Banco do Brasil há 3 anos. Trabalha diariamente em projetos que envolvem o JBoss Seam, e sempre atento as últimas novidades e plugins. Ministra treinamentos na unidade Brasília da Caelum e contribuidor da revista MundoJ.', 'Além do CDI com Seam 3', '44');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Rebecca Parsons', 'Dr. Rebecca Parsons é CTO da ThoughtWorks.Ela tem mais de 20 anos de experiência em desenvolvimento em empresas indo de telecomunicações a serviços de internet. Rebecca tem livros publicados em linguagens e inteligência artificial, serviou em diversos comitês e é também revisora de diversos jornais de artigos técnicos. Ela tem ampla experiência na criação de sistemas distribuídos de alta escala e na integração de sistemas heterogêneos. Antes da ThoughtWorks, ela trabalhou como professora assistante na University of Central Florida, onde ministrou cursos de compiladores, otmizadores, computação distribuída, linguagens, teoria da computabilidade, machine learning e biologia computacional. Rebecca é graduada em computação e economia pela Bradley University, mestrado pela Rice University e seu Ph.D. em computação na mesma universidade.', 'Evolutionary Architecture - Como fazê-la funcionar', '45');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Renato Lucindo', 'Renato Lucindo é Especialista em Arquitetura de Sistemas e Desenvolvedor Sênior no UOL, tendo também passado por outras empresas de Internet como a Globo.com. Trabalhou com sistemas de e-mail, armazenamento distribuído, sistemas inteligentes de combate a spam, e recentemente, de controle de cloud computing. Formado em Computação pela PUC-SP e Mestre em Ciência da Computação em Otimização Combinatória pela USP. ', 'Apresentação', '46');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Renato Willi', 'Renato Willi é formado em Ciência da Computação na UnB, Pós-Graduado em Implantação de Software Livre na UNISUL, MBA em Projetos pela FGV e cursa MBA em Gestão Estratégica na USP. Trabalha como Diretor e Coach na SEA Tecnologia, utilizando metodologias Ágeis. Colaborador na tradução do Manifesto Ágil e dos livros Whys Poignant Guide to Ruby, Scrum and XP from the Trenches  e  Kanban and Scrum - making the best of both , nos 2 últimos como organizador e tradutor. Palestrante em diversos eventos sobre agilidade, como Agile Brazil 2010 e 2011, Scrum Gathering Brazil 2009, Agile Weekend 2009, Àgiles 2009, Falando em Agile 2008, e diversos Marés de Agilidade - DF, BA, CE, PA, MG, VIX - de que é um dos fundadores e organizadores. Certificado como PMP, ITIL-F, SCJP, IBM RMUC e IBM RUP Specialist. (Ninguém é perfeito)', '#Fail - Onde erramos e o que aprendemos com isso?', '47');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Ricardo Valeriano', 'participou da equipe que desenvolveu um serviço chamado hpG e, durante esse trabalho, se apaixonou por desenvolvimento para web. Desde então teve experiências com diversas linguagens de programação e tecnologias, e passou a se interessar e estudar cada vez mais metodologias ágeis de desenvolvimento. Aprendeu a gostar muito de JavaScript e partilha da impressão de muitos: essa é mais incompreendida entre todas as linguagens de programação. Recentemente desenvolveu software para dispositivos móveis, sobretudo o iPhone e o iPad.', '', '48');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Roberto Gaiser', 'Trabalha há mais de 15 anos com Unix/Linux/FreeBSD em ambientes de alta disponibilidade, estando diretamente envolvido em soluções de larga escala para web, e-mail e streaming de vídeo. Atua hoje na arquitetura de sistemas e tem interesses em sistemas de coleta de estatísticas, armazenamento de dados e extração de informação a partir de grandes volumes de dados.', 'Fazendo mais com menos, da infraestrutura tradicional para a Amazon. Como o R7 entrega conteúdo a partir do AWS', '49');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Roberval Ribeiro', 'Roberval Aratame Ribeiro é Gerente de Projetos na área de Pesquisa e Desenvolvimento de IaaS e SaaS do UOL Host. Com a experiência adquirida do Portal UOL passou por diversos projetos de grande portes e de larga escala, muito desses baseando-se em soluções de sistemas distribuídos - tais como sistema de autenticação, e-mail, antispam, publicação de conteúdo mobile, etc. Formado em Ciência da Computação pela PUC-SP e tem MBA pela FGV. ', 'Programação distribuída para os problemas do dia-a-dia', '50');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Rodolpho Ugolini', 'Comecei a desenvolver software aos 9 anos quando ganhei meu primeiro computador (um TK-2000 sem gravador de fita cassette) e ingressei no Clube dos Applemaníacos. De lá para cá nunca parei e experimentei muitas linguagens como Basic, Assembly, Clipper, Pascal, C, Visual Basic, C# e Java, entre outras (não consigo gostar de Javascript, mas estou encantado com Ruby e Python). Participei de muitos projetos, grandes, pequenos, simples e complexos, tendo liderado muitos deles, para empresas de vários segmentos, sobretudo industrial e financeiro. Trabalhei em bancos e seguradoras onde tive a oportunidade de aprender sobre as mazelas do desenvolvimento de software corporativo (e a abominar processos em cascata). Trabalho na IBM como Arquiteto de Sistemas de Software da brand Rational, onde auxilio times de desenvolvimento a aprimorarem sua eficiência no desenvolvimento de software. ', 'Ferramentas ou processos não vão te salvar', '51');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Rodrigo Campos', 'Rodrigo Campos é especialista em sistemas distribuídos com foco em serviços para a Internet, estando diretamente envolvido com projetos de larga escala para tráfego e armazenamento de e-mail, transmissão de vídeo, sistemas de medição de audiência e distribuição de conteúdo. Atualmente tem pesquisado sistemas de análise de linguagem natural para a web e modelagem de sistemas distribuídos para viabilizar o planejamento de capacidade, com foco em identificação de limites de componentes e problemas de escalabilidade. ', 'Performance Oriented Design', '52');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Rodrigo Kumpera', 'Rodrigo Kumpera, engenheiro fulltime agora pela Xamarin trabalhando no Mono a quase meia década em projetos como sandboxing e hardening do runtime, o novo garbage collector e extensões vetoriais. Possui um blog em kumpera.net/blog e twitta aletoriedades em @kumpera ', 'Levando .net onde você jamais imaginou', '53');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Saulo Arruda', 'Saulo Arruda é sócio e um dos fundadores da Jera. É o cabeça dos produtos para web da empresa e dá bastante pitaco sobre o desenvolvimento de games e aplicações mobile. Também é organizador de eventos e fundador de grupos de usuários em Campo Grande/MS. ', '5 anos em 1 - aprendendo a empreender', '54');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Sérgio Lopes', 'Bacharelando em Ciência da Computação na USP, desenvolvedor desde 2002 e coordenador da unidade de São Paulo. Possui as certificações de programador (SCJP) e arquiteto (SCEA5), é moderador do GUJ e ativo participante da comunidade através de palestras, cursos e artigos. Trabalha com Java para Web e dispositivos móveis, além de ministrar vários cursos na Caelum. ', 'Por uma Web mais rápida: Técnicas de otimização de Sites', '55');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Shay Frendt', 'Shay Frendt gets a real kick out of building profitable products from scratch, especially by leveraging shiny futuristic technology and trendy business tricks like Hypothesis Driven Development. In fact, he is even conned a few conference planners into letting him give talks like Getting to Minimum Viable Product and Teams That Ship Have More Fun!. Shay works at Relevance in Durham, North Carolina and likes snowboarding, scuba diving, playing the drums, and microbrews! ', 'Organization db:migrate; going from rails dev to iPad development', '56');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Vinícius Baggio', 'Bacharel em Ciências da computação pela USP São Carlos, já trabalhou com linguagens como ASP (não, não a .NET), PHP, Python e Java, até se apaixonar por Ruby e Rails. Contribuidor de diversos projetos open-source, sempre que pode, divide suas experiências como engenheiro de software na PlataformaTec nos encontros e eventos da comunidade Ruby on Rails de São Paulo. ', 'Criando aplicações melhores com Ruby e Rails', '57');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Vinicius Quaiato', 'Vinicius Quaiato desenvolve software há 4 anos e é apaixonado por isso. Não possui pretensões gerenciais. Adora padrões, arquitetura, e código. É articulista da maior revista sobre plataforma .NET do país, palestrante em diversos eventos técnicos abordando temas como ASP.NET MVC, Windows Azure, TDD e testes, arquitetura, padrões e boas práticas, IronRuby e outros mais. É um dos líderes da comunidade .NET Architects e atualmente é coordenador do time de desenvolvimento em .NET na Gonow Tecnologia. Pai, santista fanático e evegetariano. Mantém um blog sobre arquitetura e a plataforma .NET, e gosta de encher o saco no Twitter.', 'Apresentação', '58');",
	"insert into palestrante (nome, perfil, palestra, foto) values('Wladimir Domingues', 'Entusiasta de tecnologia, formado em engenharia da computação pela UFSCar, mestre em engenharia de software pelo IPT, doutorando em IHC na POLI-USP. Atua a cerca de 15 anos com desenvolvimento de software, instrutor na Sun Microsystems por mais de 8 anos. Atualmente à frente da área de projetos e soluções no Lab360.', 'Aplicações Móveis Híbridas: usando Web e Nativo juntos', '59');"

	};

	// Nome do banco
	private static final String NOME_BANCO = "delx_palestrante";

	// Controle de vers�o
	private static final int VERSAO_BANCO = 1;

	// Nome da tabela
	public static final String TABELA_PALESTRANTE = "palestrante";

	// Classe utilit�ria para abrir, criar, e atualizar o banco de dados
	private SQLiteHelper dbHelper;

	// Cria o banco de dados com um script SQL
	public RepositorioPalestranteScript(Context ctx) {
		// Criar utilizando um script SQL
		dbHelper = new SQLiteHelper(ctx, RepositorioPalestranteScript.NOME_BANCO, RepositorioPalestranteScript.VERSAO_BANCO,
				RepositorioPalestranteScript.SCRIPT_DATABASE_CREATE, RepositorioPalestranteScript.SCRIPT_DATABASE_DELETE);

		// abre o banco no modo escrita para poder alterar tamb�m
		db = dbHelper.getWritableDatabase();
	}

	// Fecha o banco
	@Override
	public void fechar() {
		super.fechar();
		if (dbHelper != null) {
			dbHelper.close();
		}
	}
}
